// jitcache-host: bun
// jitcache-runs: Producer; Consumer
// jitcache-runs: Producer; Consumer
// jitcache-expect-no-install: 1:1

// SPEC-ucb.md section 13.3, start-line.js, F21 and I23: a body's context records the first line of the source it was
// produced from. One text holds a class with instance fields, a static block and a nested class, nine bodies in all:
// the program; StartLineOuter's default constructor, instance field initializer, static initializer and method; and,
// generated by that static initializer, which evaluates the static fields and the static block, the static block's own
// function (StaticBlockFunctionCallNode calls it), the nested class's default constructor, instance field initializer
// and innerMethod. The program's loop runs 1,000 times: the LLInt counts one point per iteration and compiles the
// program for the baseline at 500 (thresholdForJITAfterWarmUp), so the Producer captures the program too.
// Each Producer runs the text through vm.Script under lineOffset 0; each Consumer runs it under the lineOffset its
// sequence index picks, 0 then 10.
// - Under 0 each of the nine bodies imports (statistics).
// - Under 10 none imports. The program, the static block's function, method and innerMethod miss Context: each one's
//   linked source starts on its absolute line. The three field initializers miss Holder: their linked source starts on
//   line 1 under any first line (F21), while their class element definitions hold absolute lines. So do the two default
//   constructors, whose linked source is the builtin default constructor's own text, the same under any first line
//   (UnlinkedFunctionExecutable::linkedSourceCode), while their class source holds the class's absolute first line. That
//   Consumer installs nothing of the text.
// The twins pass at every import, and the stack traces of errors thrown in a field initializer and in the static block
// equal the JITCache-off run in both Consumers.
//
// The Producer and the Consumer of a sequence run with the same options, so the runner compares both with one Off run
// (SPEC-integrator.harness.md section 7.6), which follows the Consumer path (SPEC-integrator.md R-ALL-4) and so prints
// the traces under the Consumer's lineOffset. The Producer prints those traces too: after its capture it throws from the
// text with one trailing space, under its Consumer's lineOffset. Throwing from the text itself would show 0's lines in
// the field initializers and the static block, since the CodeCache serves the text the UCB generated under 0 at any
// lineOffset (F21), while the changed text misses the CodeCache and is generated afresh, as the Consumer's text is.
//
// The text names its fields with identifiers the VM makes when it is created (CommonIdentifiers: value, count, target
// and index), as SPEC-integrator.harness.md section 7.5 asks. The twin check parses each imported field initializer
// again, which leaks its field names as the native parse does; inside the imported program the decode would be the
// first to allocate any other name, so the leak would show a stack no oracle run reports.
const vm = require("node:vm");
const { context } = require("./resources/ucb-bun.js");

const t = context();
const consumerLineOffset = t.sequence === 1 ? 10 : 0;

// What the text calls back into; `throwFrom` names the place an evaluation throws from, at its first round.
let throwFrom = null;
globalThis.startLineValue = (where, round) => {
    if (where === throwFrom)
        throw new Error(`thrown from the ${where}`);
    return round;
};
// The Producer runs startLineValue hot, so a Consumer imports it at its first call, which happens here, before the
// statistics window, so that the window counts the text's bodies alone.
startLineValue("warm-up", 0);

// The text declares nothing at its top level, so evaluating it again redeclares nothing.
const text = `
{
    let startLineTotal = 0;
    for (let round = 0; round < 1000; ++round) {
        class StartLineOuter {
            value = startLineValue("field initializer", round);
            static count = 7;
            static {
                startLineValue("static block", round);
            }
            static target = class {
                index = round * 2;
                innerMethod() { return this.index + 1; }
            };
            method(x) { return this.value + x; }
        }
        const outer = new StartLineOuter();
        startLineTotal += outer.method(round) + new StartLineOuter.target().innerMethod();
    }
    startLineTotal;
}
`;

function evaluate(source, lineOffset)
{
    return new vm.Script(source, { filename: "start-line-text.js", lineOffset }).runInThisContext();
}

const before = t.statistics();
const total = evaluate(text, t.role === "Producer" ? 0 : consumerLineOffset);
const after = t.statistics();
if (t.role === "Consumer" && consumerLineOffset === 0)
    t.expect("the text under lineOffset 0", t.delta(before, after), { imports: 9 });
if (t.role === "Consumer" && consumerLineOffset === 10)
    t.expect("the text under lineOffset 10", t.delta(before, after), { imports: 0, "misses.Context": 4, "misses.Holder": 5 });
console.log(`total ${total}`);

const thrownText = t.role === "Producer" ? `${text} ` : text;
for (const where of ["field initializer", "static block"]) {
    throwFrom = where;
    try {
        evaluate(thrownText, consumerLineOffset);
        console.log(`nothing was thrown from the ${where}`);
    } catch (error) {
        console.log(error.stack);
    }
}
throwFrom = null;
t.finish();
