#include "config.h"
#include "UCBTwins.h"

#if ENABLE(JITCACHE_TWINS)

#include "CachedBytecode.h"
#include "CachedTypes.h"
#include "GlobalExecutable.h"
#include "HeapIterationScope.h"
#include "JITCacheBench.h"
#include "JITCacheVMState.h"
#include "JSCInlines.h"
#include "JSCellButterfly.h"
#include "MarkedSpaceInlines.h"
#include "ParserError.h"
#include "RegExp.h"
#include "SourceCode.h"
#include "StrongInlines.h"
#include "SymbolTable.h"
#include "TwinReport.h"
#include "UCBFeedback.h"
#include "UCBRegistry.h"
#include "UCBRequests.h"
#include "UCBSections.h"
#include "UCBTwinGeneration.h"
#include "UnlinkedFunctionCodeBlock.h"
#include "UnlinkedFunctionExecutable.h"
#include "UnlinkedGlobalCodeBlock.h"
#include "UnlinkedProgramCodeBlock.h"
#include "VM.h"
#include "ValidatedBody.h"
#include <algorithm>
#include <cmath>
#include <limits>
#include <wtf/text/MakeString.h>
#include <wtf/text/StringView.h>

// Twin comparison (SPEC-ucb.md section 13.2). The UCB the engine imported, seeded or attached is compared with what the
// engine itself produces for the same request in this process: a twin generated by the native generator for an import,
// and the UCB itself for a natively decoded or live one, which is its own native twin. State the engine cannot recompute,
// the UCB feedback, is compared with the capture record the body carries (THREAD Verification). Each function reports
// every difference it finds and returns; none changes what the engine produced.

namespace JSC::JITCache {

namespace UCBTwinsInternal {

// Every difference names its body by the key in hex (harness sub-SPEC section 2).
class UCBTwinReporter {
    WTF_MAKE_NONCOPYABLE(UCBTwinReporter);

public:
    UCBTwinReporter(TwinReportSink& sink, const BodyKey& key)
        : m_sink(sink)
        , m_subject(makeString("body "_s, bodyKeyHex(key)))
    {
    }

    void difference(ASCIILiteral check, const String& what)
    {
        m_sink.difference(TwinPart::UCB, check, makeString(m_subject, ": "_s, what));
    }

private:
    TwinReportSink& m_sink;
    const String m_subject;
};

static RefPtr<CachedBytecode> ucbTwinsEncodeCore(VM& vm, const UnlinkedCodeBlock& codeBlock, const UnlinkedFunctionExecutable* holder)
{
    CoreEncodeFailure failure = CoreEncodeFailure::None;
    return encodeUnlinkedCodeBlockCore(vm, codeBlock, holder, nullptr, failure);
}

static RefPtr<CachedBytecode> ucbTwinsEncodeDescriptor(VM& vm, const UnlinkedFunctionExecutable& executable)
{
    CoreEncodeFailure failure = CoreEncodeFailure::None;
    return encodeUnlinkedFunctionExecutableDescriptor(vm, executable, nullptr, failure);
}

// Whether the UCB's core encoding, with the given holder, has exactly the body's ucb.core bytes.
static bool ucbTwinsCoreMatches(VM& vm, const UnlinkedCodeBlock& codeBlock, const UnlinkedFunctionExecutable* holder, std::span<const uint8_t> bodyCore)
{
    RefPtr<CachedBytecode> core = ucbTwinsEncodeCore(vm, codeBlock, holder);
    return core && equalSpans(core->span(), bodyCore);
}

static bool ucbTwinsIsAtomString(JSValue value)
{
    auto* string = value ? dynamicDowncast<JSString>(value) : nullptr;
    StringImpl* impl = string ? string->tryGetValueImpl() : nullptr;
    return impl && impl->isAtom();
}

// T1's second half: every string constant register is an atom, as generation leaves it (F19, codec E10).
static void ucbTwinsCheckStringConstantsAreAtoms(UnlinkedCodeBlock& codeBlock, ASCIILiteral whose, UCBTwinReporter& reporter)
{
    const auto& constants = codeBlock.constantRegisters();
    for (size_t i = 0; i < constants.size(); ++i) {
        JSValue value = constants[i].get();
        if (value && value.isString() && !ucbTwinsIsAtomString(value))
            reporter.difference("T1"_s, makeString("string constant "_s, i, " of the "_s, whose, " is not an atom"_s));
    }
}

static Vector<DFG::FrequentExitSite> ucbTwinsExitSites(UnlinkedCodeBlock& codeBlock)
{
    Vector<DFG::FrequentExitSite> sites;
    ConcurrentJSLocker locker(codeBlock.m_lock);
    codeBlock.exitProfile().forEachFrequentExitSite(locker, [&](const DFG::FrequentExitSite& site) {
        sites.append(site);
    });
    return sites;
}

// The UCB's tier-up history: didOptimize and both quick tier-up bits. Twins read it under the cell lock, as capture does
// (section 5.3, step 5). A marker's first visit to the UCB in a cycle rewrites m_age, which shares a memory location with
// the quick bits, and reads the metadata table's bit-fields, which hold didOptimize, both under that lock
// (UnlinkedCodeBlock::visitChildrenImpl). Markers reach both UCBs T4 reads: verifyImport holds its UCB in a Strong, and a
// seeded one is on the engine's stack. The lock is not recursive; no caller of T4 holds it, and nothing else is taken while
// it is held.
struct UCBTwinsTierUpHistory {
    TriState didOptimize;
    TriState quickDFGTierUp;
    bool quickFTLTierUp;
};

static UCBTwinsTierUpHistory ucbTwinsTierUpHistory(UnlinkedCodeBlock& codeBlock)
{
    Locker locker { codeBlock.cellLock() };
    return { codeBlock.didOptimize(), codeBlock.quickDFGTierUp(), codeBlock.isQuickFTLTierUp() };
}

// T4: the UCB feedback equals the capture record. The exit sites are read under the UCB's m_lock and the tier-up history
// under its cell lock, as capture reads them. Exit sites compare as a set; the LLInt counter's progress up to the float
// rounding of m_totalCount, the precision the native counter keeps (section 5.5), and exactly for a deferred record.
static void ucbTwinsCompareFeedback(UnlinkedCodeBlock& codeBlock, const FeedbackSection& section, UCBTwinReporter& reporter)
{
    const FeedbackCounts& counts = section.counts();
    if (liveFeedbackCounts(codeBlock) != counts) {
        reporter.difference("T4"_s, "the UCB's feedback counts differ from the capture record's"_s);
        return;
    }

    for (unsigned i = 0; i < counts.valueProfiles; ++i) {
        SpeculatedType live = codeBlock.unlinkedValueProfiles()[i].prediction();
        if (live != section.prediction(i))
            reporter.difference("T4"_s, makeString("value prediction "_s, i, " is "_s, live, ", the capture record holds "_s, section.prediction(i)));
    }
    for (unsigned i = 0; i < counts.arrayProfiles; ++i) {
        auto& profile = codeBlock.unlinkedArrayProfiles()[i];
        if (profile.observedArrayModes() != section.observedArrayModes(i) || profile.arrayProfileFlags() != section.arrayProfileFlags(i))
            reporter.difference("T4"_s, makeString("array profile "_s, i, " differs from the capture record"_s));
    }
    for (unsigned i = 0; i < counts.binaryArithProfiles; ++i) {
        if (codeBlock.binaryArithProfile(i).bits() != section.binaryArithBits(i))
            reporter.difference("T4"_s, makeString("binary arithmetic profile "_s, i, " differs from the capture record"_s));
    }
    for (unsigned i = 0; i < counts.unaryArithProfiles; ++i) {
        if (codeBlock.unaryArithProfile(i).bits() != section.unaryArithBits(i))
            reporter.difference("T4"_s, makeString("unary arithmetic profile "_s, i, " differs from the capture record"_s));
    }

    Vector<DFG::FrequentExitSite> liveSites = ucbTwinsExitSites(codeBlock);
    bool sameSites = liveSites.size() == counts.exitSites;
    for (unsigned i = 0; sameSites && i < counts.exitSites; ++i)
        sameSites = liveSites.contains(section.exitSite(i));
    if (!sameSites)
        reporter.difference("T4"_s, "the exit sites differ from the capture record's"_s);

    UCBTwinsTierUpHistory history = ucbTwinsTierUpHistory(codeBlock);
    if (history.didOptimize != section.didOptimize())
        reporter.difference("T4"_s, "didOptimize differs from the capture record"_s);
    if (history.quickDFGTierUp != section.quickDFGTierUp() || history.quickFTLTierUp != section.quickFTLTierUp())
        reporter.difference("T4"_s, "a quick tier-up bit differs from the capture record"_s);

    BaselineExecutionCounter& counter = codeBlock.llintExecuteCounter();
    int32_t threshold = section.llintActiveThreshold();
    double progress = section.llintProgress();
    bool counterMatches = counter.m_activeThreshold == threshold;
    if (counterMatches) {
        if (threshold == std::numeric_limits<int32_t>::max())
            counterMatches = counter.count() == progress;
        else
            counterMatches = std::abs(counter.count() - progress) <= std::max<double>(std::abs(counter.m_totalCount), 1.0) * 0x1p-23;
    }
    if (!counterMatches)
        reporter.difference("T4"_s, makeString("the LLInt counter holds threshold "_s, counter.m_activeThreshold, " and progress "_s, counter.count(), ", the capture record "_s, threshold, " and "_s, progress));

    for (unsigned i = 0; i < counts.functionDecls; ++i) {
        if (codeBlock.functionDecl(i)->singletonHasBeenInvalidated() != section.childSingletonInvalidated(ChildTable::Declarations, i))
            reporter.difference("T4"_s, makeString("the singleton bit of function declaration "_s, i, " differs from the capture record"_s));
    }
    for (unsigned i = 0; i < counts.functionExprs; ++i) {
        if (codeBlock.functionExpr(i)->singletonHasBeenInvalidated() != section.childSingletonInvalidated(ChildTable::Expressions, i))
            reporter.difference("T4"_s, makeString("the singleton bit of function expression "_s, i, " differs from the capture record"_s));
    }
    const auto& constants = codeBlock.constantRegisters();
    for (unsigned i = 0; i < counts.constants; ++i) {
        JSValue value = constants[i].get();
        auto* symbolTable = value ? dynamicDowncast<SymbolTable>(value) : nullptr;
        bool invalidated = symbolTable && symbolTable->singleton().hasBeenInvalidated();
        if (invalidated != section.constantSingletonInvalidated(i))
            reporter.difference("T4"_s, makeString("the scope singleton of constant "_s, i, " differs from the capture record"_s));
    }
}

// T2. A UFE body's restored parse fields are its UFE's three fields; a global's or a direct eval's are its executable's,
// and its UCB's directives.
static void ucbTwinsCompareFunctionParseFields(const UnlinkedFunctionExecutable& executable, const TwinParseResults& results, UCBTwinReporter& reporter)
{
    if (executable.features() != results.features)
        reporter.difference("T2"_s, makeString("the UFE's features are "_s, executable.features(), ", the twin's "_s, results.features));
    if (executable.lexicallyScopedFeatures() != results.lexicallyScopedFeatures)
        reporter.difference("T2"_s, makeString("the UFE's lexically scoped features are "_s, executable.lexicallyScopedFeatures(), ", the twin's "_s, results.lexicallyScopedFeatures));
    if (executable.hasCapturedVariables() != results.hasCapturedVariables)
        reporter.difference("T2"_s, "the UFE's captured-variables bit differs from the twin's"_s);
}

static bool ucbTwinsSameDirective(StringImpl* a, StringImpl* b)
{
    return WTF::equal(a, b);
}

static void ucbTwinsCompareGlobalParseFields(GlobalExecutable& executable, UnlinkedGlobalCodeBlock& imported, UnlinkedGlobalCodeBlock& twin, const TwinParseResults& results, UCBTwinReporter& reporter)
{
    if (executable.features() != results.features)
        reporter.difference("T2"_s, makeString("the executable's features are "_s, executable.features(), ", the twin's "_s, results.features));
    if (executable.lexicallyScopedFeatures() != results.lexicallyScopedFeatures)
        reporter.difference("T2"_s, makeString("the executable's lexically scoped features are "_s, executable.lexicallyScopedFeatures(), ", the twin's "_s, results.lexicallyScopedFeatures));
    // ScriptExecutable keeps its captured-variables bit private; recordParseFromUnlinkedCodeBlock copied it from the UCB.
    if (imported.hasCapturedVariables() != results.hasCapturedVariables)
        reporter.difference("T2"_s, "the captured-variables bit the import restored differs from the twin's"_s);
    if (static_cast<int>(executable.lastLine()) != results.lastLine)
        reporter.difference("T2"_s, makeString("the executable's last line is "_s, executable.lastLine(), ", the twin's "_s, results.lastLine));
    if (executable.endColumn() != results.endColumn)
        reporter.difference("T2"_s, makeString("the executable's end column is "_s, executable.endColumn(), ", the twin's "_s, results.endColumn));
    if (!ucbTwinsSameDirective(imported.sourceURLDirective(), twin.sourceURLDirective()) || !ucbTwinsSameDirective(imported.sourceMappingURLDirective(), twin.sourceMappingURLDirective()))
        reporter.difference("T2"_s, "the imported UCB's directives differ from the twin's"_s);
}

// T3: the declarations iterate in the same order, entry by entry, flags included (F10).
static bool ucbTwinsSameDeclarationOrder(const VariableEnvironment& a, const VariableEnvironment& b)
{
    if (a.mapSize() != b.mapSize())
        return false;
    auto other = b.begin();
    for (const auto& entry : a) {
        if (other == b.end() || entry.key.get() != other->key.get() || !(entry.value == other->value))
            return false;
        ++other;
    }
    return true;
}

// The number of links of a TDZ chain, and the position of `target` on it, if the chain reaches it.
struct UCBTwinsChainShape {
    unsigned length { 0 };
    std::optional<unsigned> targetPosition;
};

static UCBTwinsChainShape ucbTwinsChainShape(TDZEnvironmentLink* link, const TDZEnvironmentLink* target)
{
    UCBTwinsChainShape shape;
    for (; link; link = link->parent()) {
        if (target && link == target && !shape.targetPosition)
            shape.targetPosition = shape.length;
        ++shape.length;
    }
    return shape;
}

// T5. A child's fields are its descriptor, which the codec writes from every field generation reads except its own slots,
// its own parse fields and its TDZ chain (codec E1, E2, E14), so equal descriptors are equal fields. The parse fields must
// be unparsed in both. The links keep their environments private, so the chains compare by shape here: the same number of
// links, ending in the requesting UFE's own chain object at the same link. The environments of the links before that are
// written link by link into the core, which T1 compares. The chains are not digested here: an environment keeps its first
// digest, so a twin that took it would leave it out of the tdzEnvironmentDigests count of the engine's next holder digest
// (section 6.5), and twins runs would count otherwise than runs without twins.
static void ucbTwinsCompareChildren(VM& vm, UnlinkedCodeBlock& imported, UnlinkedCodeBlock& twin, const UnlinkedFunctionExecutable* holder, UCBTwinReporter& reporter)
{
    if (imported.numberOfFunctionDecls() != twin.numberOfFunctionDecls() || imported.numberOfFunctionExprs() != twin.numberOfFunctionExprs()) {
        reporter.difference("T5"_s, "the import and the twin have different numbers of children"_s);
        return;
    }
    const TDZEnvironmentLink* holderChain = holder ? holder->parentScopeTDZVariables().get() : nullptr;

    auto compare = [&](UnlinkedFunctionExecutable* child, UnlinkedFunctionExecutable* twinChild, ASCIILiteral table, size_t index) {
        if (!child || !twinChild) {
            reporter.difference("T5"_s, makeString("the "_s, table, ' ', index, " is missing from the import or the twin"_s));
            return;
        }
        RefPtr<CachedBytecode> descriptor = ucbTwinsEncodeDescriptor(vm, *child);
        RefPtr<CachedBytecode> twinDescriptor = ucbTwinsEncodeDescriptor(vm, *twinChild);
        if (!descriptor || !twinDescriptor || !equalSpans(descriptor->span(), twinDescriptor->span()))
            reporter.difference("T5"_s, makeString("the fields of the "_s, table, ' ', index, " differ from the twin's"_s));
        if (child->features() || child->hasCapturedVariables() || twinChild->features() || twinChild->hasCapturedVariables())
            reporter.difference("T5"_s, makeString("the "_s, table, ' ', index, " has parse fields that are not unparsed"_s));
        if (child->lexicallyScopedFeatures() != twinChild->lexicallyScopedFeatures())
            reporter.difference("T5"_s, makeString("the lexically scoped features of the "_s, table, ' ', index, " differ from the twin's"_s));
        UCBTwinsChainShape shape = ucbTwinsChainShape(child->parentScopeTDZVariables().get(), holderChain);
        UCBTwinsChainShape twinShape = ucbTwinsChainShape(twinChild->parentScopeTDZVariables().get(), holderChain);
        if (shape.length != twinShape.length || shape.targetPosition != twinShape.targetPosition)
            reporter.difference("T5"_s, makeString("the TDZ chain of the "_s, table, ' ', index, " does not have the twin's links over the requesting UFE's chain"_s));
    };
    for (size_t i = 0; i < imported.numberOfFunctionDecls(); ++i)
        compare(imported.functionDecl(static_cast<int>(i)), twin.functionDecl(static_cast<int>(i)), "function declaration"_s, i);
    for (size_t i = 0; i < imported.numberOfFunctionExprs(); ++i)
        compare(imported.functionExpr(static_cast<int>(i)), twin.functionExpr(static_cast<int>(i)), "function expression"_s, i);
}

// T6: the constant cells have the twin's forms, which the core bytes do not show (codec E10, E11 and E16).
static void ucbTwinsCompareConstantCells(VM& vm, UnlinkedCodeBlock& imported, UnlinkedCodeBlock& twin, UCBTwinReporter& reporter)
{
    const auto& constants = imported.constantRegisters();
    const auto& twinConstants = twin.constantRegisters();
    if (constants.size() != twinConstants.size()) {
        reporter.difference("T6"_s, "the import and the twin have different numbers of constants"_s);
        return;
    }
    JSValue sentinel = vm.orderedHashTableSentinel();
    Structure* atomStringsStructure = vm.cellButterflyOnlyAtomStringsStructure.get();
    auto holdsCanonicalAtoms = [&](JSCellButterfly& butterfly) {
        for (unsigned i = 0; i < butterfly.length(); ++i) {
            JSValue element = butterfly.get(i);
            auto* string = element ? dynamicDowncast<JSString>(element) : nullptr;
            StringImpl* impl = string ? string->tryGetValueImpl() : nullptr;
            if (!impl || !impl->isAtom() || vm.atomStringToJSStringMap.get(impl) != string)
                return false;
        }
        return true;
    };
    for (size_t i = 0; i < constants.size(); ++i) {
        JSValue value = constants[i].get();
        JSValue twinValue = twinConstants[i].get();
        // The VM's ordered-hash-table sentinel is a zero-length butterfly that builtins compare by pointer (F27), so the
        // import must hold the very cell, not one of its form.
        if (twinValue == sentinel) {
            if (value != sentinel)
                reporter.difference("T6"_s, makeString("constant "_s, i, " is not the VM's ordered-hash-table sentinel, which the twin holds there"_s));
            continue;
        }
        if (auto* twinButterfly = twinValue ? dynamicDowncast<JSCellButterfly>(twinValue) : nullptr) {
            auto* butterfly = value ? dynamicDowncast<JSCellButterfly>(value) : nullptr;
            if (!butterfly || butterfly->structure() != twinButterfly->structure()) {
                reporter.difference("T6"_s, makeString("butterfly constant "_s, i, " does not have the twin's structure"_s));
                continue;
            }
            if (butterfly->structure() == atomStringsStructure && (!holdsCanonicalAtoms(*butterfly) || !holdsCanonicalAtoms(*twinButterfly)))
                reporter.difference("T6"_s, makeString("an element of butterfly constant "_s, i, " is not the JSString atomStringToJSStringMap holds for its atom"_s));
            continue;
        }
        if (twinValue && dynamicDowncast<RegExp>(twinValue)) {
            if (value != twinValue)
                reporter.difference("T6"_s, makeString("RegExp constant "_s, i, " is not the cell the twin holds"_s));
        }
    }
}

// Generates the twin of the request's native generation. A global or direct-eval parse writes the provider's directives
// (section 13.2), so they are snapshotted first, compared after the twin for T2 and then restored, leaving the provider as
// a run without twins leaves it.
static UnlinkedCodeBlock* ucbTwinsGenerate(const RequestState& state, TwinParseResults& results, ParserError& error, UCBTwinReporter& reporter)
{
    if (state.kind == RequestKind::FunctionBody)
        return generateFunctionBodyTwin(state, results, error);

    SourceProvider* provider = state.source.provider();
    String sourceURLDirective = provider->sourceURLDirective();
    String sourceMappingURLDirective = provider->sourceMappingURLDirective();
    UnlinkedCodeBlock* twin = generateGlobalTwin(state, results, error);
    if (twin && (provider->sourceURLDirective() != sourceURLDirective || provider->sourceMappingURLDirective() != sourceMappingURLDirective))
        reporter.difference("T2"_s, "the provider's directives as the import left them differ from what the native parse writes"_s);
    provider->setSourceURLDirective(sourceURLDirective);
    provider->setSourceMappingURLDirective(sourceMappingURLDirective);
    return twin;
}

} // namespace UCBTwinsInternal

void verifyImport(const RequestState& state, UnlinkedCodeBlock& imported, const ValidatedBody& body, TwinReportSink& sink)
{
    using namespace UCBTwinsInternal;

    VM& vm = state.vm;
    UCBTwinReporter reporter(sink, body.key());
    bool isFunctionBody = state.kind == RequestKind::FunctionBody;
    const UnlinkedFunctionExecutable* holder = isFunctionBody ? state.functionExecutable : nullptr;

    // The imported UCB is on the engine's stack; both are held here, since the comparisons below outlast the generation.
    Strong<UnlinkedCodeBlock> importedHandle { vm, &imported };
    TwinParseResults results;
    ParserError error;
    Strong<UnlinkedCodeBlock> twinHandle { vm, ucbTwinsGenerate(state, results, error, reporter) };
    if (!twinHandle) {
        // The producer generated this body from the same inputs, so a twin that cannot be generated is a difference.
        reporter.difference("T1"_s, makeString("the twin's generation failed: "_s, error.message()));
        return;
    }
    UnlinkedCodeBlock& twin = *twinHandle.get();

    // T1.
    std::span<const uint8_t> bodyCore = body.section(SectionKind::UCBCore);
    if (!ucbTwinsCoreMatches(vm, twin, holder, bodyCore))
        reporter.difference("T1"_s, "the twin's core encoding differs from the body's ucb.core"_s);
    if (!ucbTwinsCoreMatches(vm, imported, holder, bodyCore))
        reporter.difference("T1"_s, "the imported UCB's core encoding differs from the body's ucb.core"_s);
    ucbTwinsCheckStringConstantsAreAtoms(imported, "import"_s, reporter);
    ucbTwinsCheckStringConstantsAreAtoms(twin, "twin"_s, reporter);

    // T2.
    if (isFunctionBody)
        ucbTwinsCompareFunctionParseFields(*state.functionExecutable, results, reporter);
    else
        ucbTwinsCompareGlobalParseFields(*state.globalExecutable, uncheckedDowncast<UnlinkedGlobalCodeBlock>(imported), uncheckedDowncast<UnlinkedGlobalCodeBlock>(twin), results, reporter);

    // T3.
    if (state.kind == RequestKind::Program) {
        auto& importedProgram = uncheckedDowncast<UnlinkedProgramCodeBlock>(imported);
        auto& twinProgram = uncheckedDowncast<UnlinkedProgramCodeBlock>(twin);
        if (!ucbTwinsSameDeclarationOrder(importedProgram.variableDeclarations(), twinProgram.variableDeclarations()))
            reporter.difference("T3"_s, "the variable declarations iterate in another order than the twin's"_s);
        if (!ucbTwinsSameDeclarationOrder(importedProgram.lexicalDeclarations(), twinProgram.lexicalDeclarations()))
            reporter.difference("T3"_s, "the lexical declarations iterate in another order than the twin's"_s);
    }

    // T4, against the capture record the body carries. The import parsed it already; strict off reads it where the layout
    // puts each field.
    if (auto feedback = FeedbackSection::parse(body.section(SectionKind::UCBFeedback), false))
        ucbTwinsCompareFeedback(imported, *feedback, reporter);

    // T5 and T6.
    ucbTwinsCompareChildren(vm, imported, twin, holder, reporter);
    ucbTwinsCompareConstantCells(vm, imported, twin, reporter);
}

void verifyMatched(UnlinkedCodeBlock& codeBlock, const UnlinkedFunctionExecutable* holder, bool seeded, const ValidatedBody& body, TwinReportSink& sink)
{
    using namespace UCBTwinsInternal;

    VM& vm = codeBlock.vm();
    UCBTwinReporter reporter(sink, body.key());

    // The natively decoded or live UCB is its own native twin: its encoding must be the body's core (section 7.3.2).
    if (!ucbTwinsCoreMatches(vm, codeBlock, holder, body.section(SectionKind::UCBCore)))
        reporter.difference("T1"_s, makeString("the core encoding of the "_s, seeded ? "seeded"_s : "attached"_s, " UCB differs from the body's ucb.core"_s));

    // Every constant the atom map marks is an atom before a CodeBlock installs the body (section 9.1).
    if (auto identity = parseIdentitySection(body.section(SectionKind::UCBIdentity), false)) {
        const auto& constants = codeBlock.constantRegisters();
        for (uint32_t i = 0; i < identity->constantCount; ++i) {
            if (!((identity->atomMap[i / 8] >> (i % 8)) & 1))
                continue;
            if (i >= constants.size() || !ucbTwinsIsAtomString(constants[i].get()))
                reporter.difference("T1"_s, makeString("constant "_s, i, ", which the atom map marks, is not an atom"_s));
        }
    }

    if (seeded) {
        if (auto feedback = FeedbackSection::parse(body.section(SectionKind::UCBFeedback), false))
            ucbTwinsCompareFeedback(codeBlock, *feedback, reporter);
    }
}

void verifySuppliedDigest(const SourceCode& rootSource, const RootSourceDigest& digest, TwinReportSink& sink)
{
    // T7, whatever strict says. Only a digest taken from where the text was produced needs its text; a computed one is it.
    if (digest.origin == SourceDigestOrigin::Computed)
        return;
    if (sourceDigest(rootSource.view()) == digest.digest)
        return;
    ASCIILiteral origin = digest.origin == SourceDigestOrigin::BuiltinMetadata ? "builtin metadata"_s : "provider"_s;
    SourceProvider* provider = rootSource.provider();
    sink.difference(TwinPart::UCB, "T7"_s, makeString("the "_s, origin, " digest of the root at offsets "_s, rootSource.startOffset(), " to "_s, rootSource.endOffset(), " of "_s, provider ? provider->sourceURL() : String { }, " differs from the digest of its text"_s));
}

unsigned verifyRegistry(VM& vm, TwinReportSink* sink)
{
    VMState* state = vm.jitCacheState();
    if (!state)
        return 0;

    // A full collection ends with a synchronous sweep, so every cell that died has run its destructor and dropped its
    // entries (F12), and no entry of a dead but unswept cell reads as a violation.
    vm.heap.collectNow(Sync, CollectionScope::Full);

    Vector<UnlinkedFunctionExecutable*> liveExecutables;
    Vector<UnlinkedCodeBlock*> liveCodeBlocks;
    {
        HeapIterationScope iterationScope(vm.heap);
        vm.heap.objectSpace().forEachLiveCell(iterationScope, [&](HeapCell* cell, HeapCell::Kind kind) {
            if (!isJSCellKind(kind))
                return IterationStatus::Continue;
            auto* jsCell = static_cast<JSCell*>(cell);
            if (auto* executable = dynamicDowncast<UnlinkedFunctionExecutable>(jsCell))
                liveExecutables.append(executable);
            else if (auto* codeBlock = dynamicDowncast<UnlinkedCodeBlock>(jsCell))
                liveCodeBlocks.append(codeBlock);
            return IterationStatus::Continue;
        });
    }

    unsigned violations = 0;
    auto violation = [&](unsigned count, String detail) {
        violations += count;
        if (sink)
            sink->difference(TwinPart::UCB, "registry"_s, WTF::move(detail));
    };

    UCBRegistry& registry = state->registry();
    size_t liveChildren = 0;
    size_t liveRoots = 0;
    for (auto* executable : liveExecutables) {
        std::optional<ExecutableIdentity> identity = registry.identityOf(*executable);
        if (!identity)
            continue;
        if (std::holds_alternative<ChildIdentity>(*identity))
            ++liveChildren;
        else
            ++liveRoots;
    }

    // I8: every child UFE of a recorded UCB has the identity its parent's record gives it.
    size_t liveRecords = 0;
    for (auto* codeBlock : liveCodeBlocks) {
        std::optional<BodyKey> key = registry.keyOf(*codeBlock);
        if (!key)
            continue;
        ++liveRecords;
        auto check = [&](UnlinkedFunctionExecutable* child, ChildTable table, size_t index) {
            std::optional<ExecutableIdentity> identity = child ? registry.identityOf(*child) : std::nullopt;
            auto* childIdentity = identity ? std::get_if<ChildIdentity>(&*identity) : nullptr;
            bool fits = childIdentity && childIdentity->parent && childIdentity->parent->key() == *key && childIdentity->table == table && childIdentity->index == index;
            if (!fits)
                violation(1, makeString("I8: child "_s, index, " of table "_s, static_cast<unsigned>(table), " of the UCB recorded as body "_s, bodyKeyHex(*key), " lacks the identity its parent's record gives it"_s));
        };
        for (size_t i = 0; i < codeBlock->numberOfFunctionDecls(); ++i)
            check(codeBlock->functionDecl(static_cast<int>(i)), ChildTable::Declarations, i);
        for (size_t i = 0; i < codeBlock->numberOfFunctionExprs(); ++i)
            check(codeBlock->functionExpr(static_cast<int>(i)), ChildTable::Expressions, i);
    }

    // I2 and I3: each entry names a live cell of the VM, and a UFE has at most one identity, so the maps hold exactly the
    // entries the live cells were found with. An entry beyond those names a dead cell, or a UFE recorded twice.
    UCBRegistry::Counts counts = registry.counts();
    auto compareCount = [&](size_t entries, size_t live, ASCIILiteral map) {
        if (entries == live)
            return;
        size_t difference = entries > live ? entries - live : live - entries;
        violation(static_cast<unsigned>(std::min<size_t>(difference, std::numeric_limits<unsigned>::max())),
            makeString("I2/I3: the registry's "_s, map, " map holds "_s, entries, " entries, of which the live cells account for "_s, live));
    };
    compareCount(counts.children, liveChildren, "child"_s);
    compareCount(counts.roots, liveRoots, "root"_s);
    compareCount(counts.codeBlocks, liveRecords, "record"_s);
    return violations;
}

} // namespace JSC::JITCache

#endif // ENABLE(JITCACHE_TWINS)
